# This is a basic workflow to help you get started with Actions

name: CI pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main","develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ENV: 'test' #FBL : ici je précise à GIT ACTIONS d'utiliser l'environnement 'test' et non dev par défaut

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: check out du code
        uses: actions/checkout@v4

      - name: configuration de python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      
      - name: Installer uv et les dépendances
        run: |
          pip install uv
          uv sync --frozen

      - name: Lancer les tests
        run: uv run pytest --maxfail=1 --disable-warnings -q
